// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPB0nczsqi5uBXubUdJf0u5WwopTEQMVY',
    appId: '1:980749205851:web:4ae321174e99371a979a7e',
    messagingSenderId: '980749205851',
    projectId: 'nemu-aba25',
    authDomain: 'nemu-aba25.firebaseapp.com',
    storageBucket: 'nemu-aba25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUapQ3WL-2TYxWmKmn6HkfGWAxKoXJMp8',
    appId: '1:980749205851:android:c25c895196b278c2979a7e',
    messagingSenderId: '980749205851',
    projectId: 'nemu-aba25',
    storageBucket: 'nemu-aba25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNoUrS4iZ5qLkxqtaOVW3NEvSvTrV4gCY',
    appId: '1:980749205851:ios:d47ef06abddf5130979a7e',
    messagingSenderId: '980749205851',
    projectId: 'nemu-aba25',
    storageBucket: 'nemu-aba25.firebasestorage.app',
    iosBundleId: 'com.nemu.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNoUrS4iZ5qLkxqtaOVW3NEvSvTrV4gCY',
    appId: '1:980749205851:ios:d47ef06abddf5130979a7e',
    messagingSenderId: '980749205851',
    projectId: 'nemu-aba25',
    storageBucket: 'nemu-aba25.firebasestorage.app',
    iosBundleId: 'com.nemu.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPB0nczsqi5uBXubUdJf0u5WwopTEQMVY',
    appId: '1:980749205851:web:5667bee540abe0ca979a7e',
    messagingSenderId: '980749205851',
    projectId: 'nemu-aba25',
    authDomain: 'nemu-aba25.firebaseapp.com',
    storageBucket: 'nemu-aba25.firebasestorage.app',
  );
}
